common:
  config_name: end_to_end_ecbplus
  base_dir: /home/nobody/code/EasyECR
#  base_dir: /root/project/EasyECR
  mode: evaluate
  model_dir: ${common.base_dir}/${common.config_name}_model
  cache_dir: ${common.base_dir}/${common.config_name}_cache
  log_dir: ${common.base_dir}/${common.config_name}_log

ecr_data:
  dataset_name: ecbplus
  train_path:
  dev_path:
  test_path:
  total_path: /data/dev/ecr-data/ECB+_LREC2014

tagger:
  max_surrounding_contx: 200
  transformer_model: roberta-large

EcrFramework1:
  output_tag: event_id_pred_ecr_framework1
  parameters:
    evaluate_topic: doc_topic
    predict_topic: doc_topic
    main_metric: CoNLL
    ecr_model:
      output_tag: distance_ecr_framework1
      parameters:
        common:
          mode: ${common.mode}
          train_topic: doc_topic
          predict_topic: doc_topic
          evaluate_topic: doc_topic
          model_dir: ${common.model_dir}/ecr_framework1/
          best_model_file_name: best.ckpt
        module:
          transformer_model: roberta-large
          no_decay_params: []
          optimizer: adam
          learning_rate: 0.0005
          num_training_steps: 300000
          model_checkpoint: ${EcrFramework1.parameters.ecr_model.parameters.common.model_dir}/best.ckpt
        dataset:
          include_singleton: True
          times: 0
        dataloader:
          train_batch_size: 32
          evaluate_batch_size: 1280
          predict_batch_size: 1280
          num_workers: 1
        trainer_parameters:
          accelerator: gpu
          gradient_clip_val: 10.0
          check_val_every_n_epoch: 1
#          val_check_interval: 10
          max_epochs: 10
          default_root_dir: ${common.log_dir}/pl
    ecr_model_output_tag: distance_ecr_framework1
    cluster_model:
      model_name: EcrAgglomerativeClustering
      parameters:
        distance_threshold: [0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 0.85, 0.9]
        best_distance:
        affinity: precomputed
    evaluator:
      parameters:
        average_over_topic: False
        metric_names: ['mentions', 'muc', 'bcub', 'ceafe', 'lea']
        keep_singletons: False
